import { homedir } from "node:os";
import { join } from "node:path";
import { writeFile, mkdir, chmod } from "node:fs/promises";
import {
  GEMINI_CONFIG_DIR,
  REVENIUM_ENV_FILE,
  CONFIG_FILE_MODE,
  ENV_VARS,
  DEFAULT_COST_MULTIPLIER,
  REVENIUM_API_KEY_ATTR,
} from "../../utils/constants.js";
import type { ReveniumConfig } from "../../types/index.js";
import { getFullOtlpEndpoint } from "./loader.js";

/**
 * Escapes a value for use in OTEL_RESOURCE_ATTRIBUTES.
 * OTEL_RESOURCE_ATTRIBUTES uses comma as delimiter and equals as key-value separator.
 * Characters that need escaping: comma (,), equals (=), and double-quote (").
 * We URL-encode these characters to ensure safe parsing.
 */
function escapeResourceAttributeValue(value: string): string {
  return value
    .replace(/%/g, "%25") // Escape % first to avoid double-encoding
    .replace(/,/g, "%2C")
    .replace(/=/g, "%3D")
    .replace(/"/g, "%22");
}

/**
 * Escapes a value for safe use in shell export statements.
 * Wraps value in single quotes and escapes any single quotes within.
 */
function escapeShellValue(value: string): string {
  // Escape single quotes by replacing ' with '\''
  const escaped = value.replace(/'/g, "'\\''");
  return `'${escaped}'`;
}

/**
 * Escapes a value for safe use in Fish shell set statements.
 * Wraps value in single quotes and escapes any single quotes and backslashes within.
 */
function escapeFishValue(value: string): string {
  // In Fish, within single quotes:
  // - Backslash is escaped as \\
  // - Single quote is escaped as \'
  const escaped = value.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
  return `'${escaped}'`;
}

/**
 * Gets the path to the Gemini config directory.
 */
function getGeminiConfigDir(): string {
  return join(homedir(), GEMINI_CONFIG_DIR);
}

/**
 * Generates the content for the revenium.env file.
 */
function generateEnvContent(config: ReveniumConfig): string {
  const fullEndpoint = getFullOtlpEndpoint(config.endpoint);

  const lines: string[] = [
    "# Revenium Gemini CLI Metering Configuration",
    "# Generated by @revenium/gemini-cli-metering",
    "#",
    "# To load these variables, add to your shell profile:",
    "#   source ~/.gemini/revenium.env",
    "",
    "# Enable Gemini CLI telemetry",
    `export ${ENV_VARS.TELEMETRY_ENABLED}=true`,
    "",
    "# Telemetry target (local = custom OTLP endpoint)",
    `export ${ENV_VARS.TELEMETRY_TARGET}=local`,
    "",
    "# OTLP endpoint for Revenium metering",
    `export ${ENV_VARS.TELEMETRY_OTLP_ENDPOINT}=${escapeShellValue(fullEndpoint)}`,
    "",
    "# OTLP protocol (http for OTLP/HTTP)",
    `export ${ENV_VARS.TELEMETRY_OTLP_PROTOCOL}=http`,
    "",
    "# Log prompts (include prompt content in telemetry)",
    `export ${ENV_VARS.TELEMETRY_LOG_PROMPTS}=true`,
  ];

  // Build resource attributes array (includes API key for authentication)
  // Note: Gemini CLI doesn't support OTEL_EXPORTER_OTLP_HEADERS, so we pass
  // the API key via OTEL_RESOURCE_ATTRIBUTES which gets included in the payload
  const resourceAttrs: string[] = [`${REVENIUM_API_KEY_ATTR}=${config.apiKey}`];

  // Add cost multiplier (validate it's a valid number)
  const costMultiplier = config.costMultiplier ?? DEFAULT_COST_MULTIPLIER;
  if (isNaN(costMultiplier) || costMultiplier <= 0) {
    throw new Error(
      `Invalid cost multiplier: ${costMultiplier}. Must be a positive number.`,
    );
  }
  resourceAttrs.push(`cost_multiplier=${costMultiplier}`);

  // Add optional email to resource attributes for attribution
  if (config.email) {
    resourceAttrs.push(
      `user.email=${escapeResourceAttributeValue(config.email)}`,
    );
    lines.push("");
    lines.push("# Subscriber email for attribution");
    lines.push(
      `export ${ENV_VARS.SUBSCRIBER_EMAIL}=${escapeShellValue(config.email)}`,
    );
  }

  // Add organization name for cost attribution
  if (config.organizationName) {
    resourceAttrs.push(
      `organization.name=${escapeResourceAttributeValue(config.organizationName)}`,
    );
    lines.push("");
    lines.push("# Organization name for cost attribution");
    lines.push(
      `export ${ENV_VARS.ORGANIZATION_NAME}=${escapeShellValue(config.organizationName)}`,
    );
  }

  // Add product name for cost attribution
  if (config.productName) {
    resourceAttrs.push(
      `product.name=${escapeResourceAttributeValue(config.productName)}`,
    );
    lines.push("");
    lines.push("# Product name for cost attribution");
    lines.push(
      `export ${ENV_VARS.PRODUCT_NAME}=${escapeShellValue(config.productName)}`,
    );
  }

  // Add cost multiplier env var
  if (
    config.costMultiplier !== undefined &&
    config.costMultiplier !== DEFAULT_COST_MULTIPLIER
  ) {
    lines.push("");
    lines.push("# Cost multiplier for pricing adjustments");
    lines.push(
      `export ${ENV_VARS.COST_MULTIPLIER}=${escapeShellValue(config.costMultiplier.toString())}`,
    );
  }

  lines.push("");
  lines.push(
    "# OTEL resource attributes (business metadata for cost attribution)",
  );
  lines.push(
    `export ${ENV_VARS.RESOURCE_ATTRIBUTES}=${escapeShellValue(resourceAttrs.join(","))}`,
  );

  // Add advanced configuration section (commented out by default)
  lines.push("");
  lines.push(
    "# ─────────────────────────────────────────────────────────────────────────────",
  );
  lines.push("# Advanced Configuration (Optional)");
  lines.push(
    "# ─────────────────────────────────────────────────────────────────────────────",
  );
  lines.push("#");
  lines.push(
    "# To add organization/product attribution manually, update OTEL_RESOURCE_ATTRIBUTES above.",
  );
  lines.push(
    '# Example: export OTEL_RESOURCE_ATTRIBUTES="cost_multiplier=1.0,organization.name=my-org,product.name=my-product"',
  );
  lines.push("#");
  if (!config.organizationName) {
    lines.push(
      "# Organization name: Attribute Gemini CLI costs to a specific customer or company.",
    );
    lines.push(`# export ${ENV_VARS.ORGANIZATION_NAME}=your-organization-name`);
  }
  if (!config.productName) {
    lines.push(
      "# Product name: Attribute Gemini CLI costs to a specific product or project.",
    );
    lines.push(`# export ${ENV_VARS.PRODUCT_NAME}=your-product-name`);
  }
  if (
    config.costMultiplier === undefined ||
    config.costMultiplier === DEFAULT_COST_MULTIPLIER
  ) {
    lines.push(
      "# Cost multiplier: Adjust pricing (default: 1.0 = no discount).",
    );
    lines.push(`# export ${ENV_VARS.COST_MULTIPLIER}=1.0`);
  }

  lines.push("");
  return lines.join("\n");
}

/**
 * Generates the content for the revenium.fish file (Fish shell compatible).
 */
function generateFishContent(config: ReveniumConfig): string {
  const fullEndpoint = getFullOtlpEndpoint(config.endpoint);

  const lines: string[] = [
    "# Revenium Gemini CLI Metering Configuration",
    "# Generated by @revenium/gemini-cli-metering",
    "#",
    "# To load these variables, add to your Fish config:",
    "#   source ~/.gemini/revenium.fish",
    "",
    "# Enable Gemini CLI telemetry",
    `set -gx ${ENV_VARS.TELEMETRY_ENABLED} true`,
    "",
    "# Telemetry target (local = custom OTLP endpoint)",
    `set -gx ${ENV_VARS.TELEMETRY_TARGET} local`,
    "",
    "# OTLP endpoint for Revenium metering",
    `set -gx ${ENV_VARS.TELEMETRY_OTLP_ENDPOINT} ${escapeFishValue(fullEndpoint)}`,
    "",
    "# OTLP protocol (http for OTLP/HTTP)",
    `set -gx ${ENV_VARS.TELEMETRY_OTLP_PROTOCOL} http`,
    "",
    "# Log prompts (include prompt content in telemetry)",
    `set -gx ${ENV_VARS.TELEMETRY_LOG_PROMPTS} true`,
  ];

  // Build resource attributes array (includes API key for authentication)
  // Note: Gemini CLI doesn't support OTEL_EXPORTER_OTLP_HEADERS, so we pass
  // the API key via OTEL_RESOURCE_ATTRIBUTES which gets included in the payload
  const resourceAttrs: string[] = [`${REVENIUM_API_KEY_ATTR}=${config.apiKey}`];

  // Add cost multiplier (validate it's a valid number)
  const costMultiplier = config.costMultiplier ?? DEFAULT_COST_MULTIPLIER;
  if (isNaN(costMultiplier) || costMultiplier <= 0) {
    throw new Error(
      `Invalid cost multiplier: ${costMultiplier}. Must be a positive number.`,
    );
  }
  resourceAttrs.push(`cost_multiplier=${costMultiplier}`);

  // Add optional email to resource attributes for attribution
  if (config.email) {
    resourceAttrs.push(
      `user.email=${escapeResourceAttributeValue(config.email)}`,
    );
    lines.push("");
    lines.push("# Subscriber email for attribution");
    lines.push(
      `set -gx ${ENV_VARS.SUBSCRIBER_EMAIL} ${escapeFishValue(config.email)}`,
    );
  }

  // Add organization name for cost attribution
  if (config.organizationName) {
    resourceAttrs.push(
      `organization.name=${escapeResourceAttributeValue(config.organizationName)}`,
    );
    lines.push("");
    lines.push("# Organization name for cost attribution");
    lines.push(
      `set -gx ${ENV_VARS.ORGANIZATION_NAME} ${escapeFishValue(config.organizationName)}`,
    );
  }

  // Add product name for cost attribution
  if (config.productName) {
    resourceAttrs.push(
      `product.name=${escapeResourceAttributeValue(config.productName)}`,
    );
    lines.push("");
    lines.push("# Product name for cost attribution");
    lines.push(
      `set -gx ${ENV_VARS.PRODUCT_NAME} ${escapeFishValue(config.productName)}`,
    );
  }

  // Add cost multiplier env var
  if (
    config.costMultiplier !== undefined &&
    config.costMultiplier !== DEFAULT_COST_MULTIPLIER
  ) {
    lines.push("");
    lines.push("# Cost multiplier for pricing adjustments");
    lines.push(
      `set -gx ${ENV_VARS.COST_MULTIPLIER} ${escapeFishValue(config.costMultiplier.toString())}`,
    );
  }

  lines.push("");
  lines.push(
    "# OTEL resource attributes (business metadata for cost attribution)",
  );
  lines.push(
    `set -gx ${ENV_VARS.RESOURCE_ATTRIBUTES} ${escapeFishValue(resourceAttrs.join(","))}`,
  );

  lines.push("");
  return lines.join("\n");
}

/**
 * Writes the Revenium configuration to ~/.gemini/revenium.env and ~/.gemini/revenium.fish.
 * Creates the directory if it doesn't exist and sets file permissions to 600.
 */
export async function writeConfig(
  config: ReveniumConfig,
): Promise<{ envPath: string; fishPath: string }> {
  const configDir = getGeminiConfigDir();
  const configPath = join(configDir, REVENIUM_ENV_FILE);
  const fishConfigPath = join(configDir, "revenium.fish");

  // Ensure the directory exists with restrictive permissions (700)
  await mkdir(configDir, { recursive: true, mode: 0o700 });

  // Generate and write the POSIX shell content (bash/zsh)
  const content = generateEnvContent(config);
  await writeFile(configPath, content, { encoding: "utf-8" });
  await chmod(configPath, CONFIG_FILE_MODE);

  // Generate and write the Fish shell content
  const fishContent = generateFishContent(config);
  await writeFile(fishConfigPath, fishContent, { encoding: "utf-8" });
  await chmod(fishConfigPath, CONFIG_FILE_MODE);

  return { envPath: configPath, fishPath: fishConfigPath };
}

/**
 * Gets the path where the config file would be written.
 */
export function getConfigFilePath(): string {
  return join(getGeminiConfigDir(), REVENIUM_ENV_FILE);
}
