import { homedir } from "node:os";
import { join } from "node:path";
import { writeFile, mkdir, chmod } from "node:fs/promises";
import {
  GEMINI_CONFIG_DIR,
  REVENIUM_ENV_FILE,
  CONFIG_FILE_MODE,
  ENV_VARS,
  REVENIUM_API_KEY_ATTR,
} from "../../utils/constants.js";
import type { ReveniumConfig } from "../../types/index.js";
import { getFullOtlpEndpoint } from "./loader.js";

/**
 * Escapes a value for use in OTEL_RESOURCE_ATTRIBUTES.
 * OTEL_RESOURCE_ATTRIBUTES uses comma as delimiter and equals as key-value separator.
 * Characters that need escaping: comma (,), equals (=), and double-quote (").
 * We URL-encode these characters to ensure safe parsing.
 */
function escapeResourceAttributeValue(value: string): string {
  return value
    .replace(/%/g, "%25") // Escape % first to avoid double-encoding
    .replace(/,/g, "%2C")
    .replace(/=/g, "%3D")
    .replace(/"/g, "%22");
}

/**
 * Gets the path to the Gemini config directory.
 */
function getGeminiConfigDir(): string {
  return join(homedir(), GEMINI_CONFIG_DIR);
}

/**
 * Generates the content for the revenium.env file.
 */
function generateEnvContent(config: ReveniumConfig): string {
  const fullEndpoint = getFullOtlpEndpoint(config.endpoint);

  const lines: string[] = [
    "# Revenium Gemini CLI Metering Configuration",
    "# Generated by @revenium/gemini-cli-metering",
    "#",
    "# To load these variables, add to your shell profile:",
    "#   source ~/.gemini/revenium.env",
    "",
    "# Enable Gemini CLI telemetry",
    `export ${ENV_VARS.TELEMETRY_ENABLED}=true`,
    "",
    "# Telemetry target (local = custom OTLP endpoint)",
    `export ${ENV_VARS.TELEMETRY_TARGET}=local`,
    "",
    "# OTLP endpoint for Revenium metering",
    `export ${ENV_VARS.TELEMETRY_OTLP_ENDPOINT}=${fullEndpoint}`,
    "",
    "# OTLP protocol (http for OTLP/HTTP)",
    `export ${ENV_VARS.TELEMETRY_OTLP_PROTOCOL}=http`,
    "",
    "# Log prompts (include prompt content in telemetry)",
    `export ${ENV_VARS.TELEMETRY_LOG_PROMPTS}=true`,
  ];

  // Build resource attributes array
  // Note: Gemini CLI doesn't support OTEL_EXPORTER_OTLP_HEADERS, so we pass
  // the API key via OTEL_RESOURCE_ATTRIBUTES which gets included in the payload
  const resourceAttrs: string[] = [`${REVENIUM_API_KEY_ATTR}=${config.apiKey}`];

  // Add optional email to resource attributes for attribution
  if (config.email) {
    resourceAttrs.push(
      `user.email=${escapeResourceAttributeValue(config.email)}`,
    );
    lines.push("");
    lines.push(
      "# Subscriber email for attribution (also in resource attributes)",
    );
    lines.push(`export ${ENV_VARS.SUBSCRIBER_EMAIL}=${config.email}`);
  }

  // Add organization name for cost attribution (support both new and old field names)
  const organizationValue = config.organizationName || config.organizationId;
  if (organizationValue) {
    resourceAttrs.push(
      `organization.name=${escapeResourceAttributeValue(organizationValue)}`,
    );
    lines.push("");
    lines.push("# Organization name for cost attribution");
    lines.push(`export ${ENV_VARS.ORGANIZATION_ID}=${organizationValue}`);
  }

  // Add product name for cost attribution (support both new and old field names)
  const productValue = config.productName || config.productId;
  if (productValue) {
    resourceAttrs.push(
      `product.name=${escapeResourceAttributeValue(productValue)}`,
    );
    lines.push("");
    lines.push("# Product name for cost attribution");
    lines.push(`export ${ENV_VARS.PRODUCT_ID}=${productValue}`);
  }

  lines.push("");
  lines.push(
    "# OTEL resource attributes (API key for authentication + optional attributes)",
  );
  lines.push(
    "# Note: Gemini CLI includes these in the OTLP payload for backend extraction",
  );
  lines.push(
    `export ${ENV_VARS.RESOURCE_ATTRIBUTES}="${resourceAttrs.join(",")}"`,
  );

  // Add advanced configuration section (commented out by default)
  lines.push("");
  lines.push(
    "# ─────────────────────────────────────────────────────────────────────────────",
  );
  lines.push("# Advanced Configuration (Optional)");
  lines.push(
    "# ─────────────────────────────────────────────────────────────────────────────",
  );
  lines.push("#");
  lines.push(
    "# To add organization/product attribution manually, update OTEL_RESOURCE_ATTRIBUTES above.",
  );
  lines.push(
    '# Example: export OTEL_RESOURCE_ATTRIBUTES="revenium.api_key=hak_xxx,organization.name=my-org,product.name=my-product"',
  );
  lines.push("#");
  if (!organizationValue) {
    lines.push(
      "# Organization Name: Attribute Gemini CLI costs to a specific customer or company.",
    );
    lines.push(`# export ${ENV_VARS.ORGANIZATION_ID}=your-organization-name`);
  }
  if (!productValue) {
    lines.push(
      "# Product Name: Attribute Gemini CLI costs to a specific product or project.",
    );
    lines.push(`# export ${ENV_VARS.PRODUCT_ID}=your-product-name`);
  }

  lines.push("");
  return lines.join("\n");
}

/**
 * Writes the Revenium configuration to ~/.gemini/revenium.env.
 * Creates the directory if it doesn't exist and sets file permissions to 600.
 */
export async function writeConfig(config: ReveniumConfig): Promise<string> {
  const configDir = getGeminiConfigDir();
  const configPath = join(configDir, REVENIUM_ENV_FILE);

  // Ensure the directory exists
  await mkdir(configDir, { recursive: true });

  // Generate and write the content
  const content = generateEnvContent(config);
  await writeFile(configPath, content, { encoding: "utf-8" });

  // Set restrictive permissions (owner read/write only)
  await chmod(configPath, CONFIG_FILE_MODE);

  return configPath;
}

/**
 * Gets the path where the config file would be written.
 */
export function getConfigFilePath(): string {
  return join(getGeminiConfigDir(), REVENIUM_ENV_FILE);
}
