export const DEFAULT_REVENIUM_URL = "https://api.revenium.ai";

export const OTLP_PATH = "/meter/v2/otlp";

export const API_KEY_PREFIX = "hak_";

export const GEMINI_CONFIG_DIR = ".gemini";

export const REVENIUM_ENV_FILE = "revenium.env";

export const CONFIG_FILE_MODE = 0o600;

export const ENV_VARS = {
  TELEMETRY_ENABLED: "GEMINI_TELEMETRY_ENABLED",
  TELEMETRY_TARGET: "GEMINI_TELEMETRY_TARGET",
  TELEMETRY_OTLP_ENDPOINT: "GEMINI_TELEMETRY_OTLP_ENDPOINT",
  TELEMETRY_OTLP_PROTOCOL: "GEMINI_TELEMETRY_OTLP_PROTOCOL",
  TELEMETRY_LOG_PROMPTS: "GEMINI_TELEMETRY_LOG_PROMPTS",
  OTLP_HEADERS: "OTEL_EXPORTER_OTLP_HEADERS",
  RESOURCE_ATTRIBUTES: "OTEL_RESOURCE_ATTRIBUTES",
  SUBSCRIBER_EMAIL: "REVENIUM_SUBSCRIBER_EMAIL",
  ORGANIZATION_NAME: "REVENIUM_ORGANIZATION_NAME",
  PRODUCT_NAME: "REVENIUM_PRODUCT_NAME",
  COST_MULTIPLIER: "REVENIUM_COST_MULTIPLIER",
} as const;

export const DEFAULT_COST_MULTIPLIER = 1.0;

/** Resource attribute key for Revenium API key */
export const REVENIUM_API_KEY_ATTR = "revenium.api_key";
